spring.application.name=UtilityPaymentPlatform
daraja.consumer-key=${DARAJA_CONSUMER_KEY}
daraja.consumer-secret=${DARAJA_CONSUMER_SECRET}
daraja.shortcode=${DARAJA_SHORTCODE}
daraja.passkey=${DARAJA_PASSKEY}
spring.data.redis.host=localhost
spring.data.redis.port=6379

token.stream-name=payment-events
token.consumer-group=token-workers
token.consumer-name=token-worker-1

water.api.base-url=
electricity.api.base-url=

#Need to confirm if the token and callback share the same worker names in redis.
