spring.application.name=UtilityPaymentPlatform
daraja.consumer-key=${DARAJA_CONSUMER_KEY}
daraja.consumer-secret=${DARAJA_CONSUMER_SECRET}
daraja.shortcode=${DARAJA_SHORTCODE}
daraja.passkey=${DARAJA_PASSKEY}
